# Generated by Django 4.1 on 2022-08-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_outlet', '0002_alter_food_chef_alter_food_name_alter_food_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_Sweet',
            field=models.BooleanField(default=True),
        ),
    ]
