# Generated by Django 4.1 on 2022-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_outlet', '0003_food_is_sweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
