# Generated by Django 4.0.5 on 2022-08-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_outlet', '0005_chef_alter_food_slug_alter_food_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food_outlet.chef'),
        ),
    ]
