# Generated by Django 4.0.5 on 2022-08-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_outlet', '0006_alter_food_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('postal', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='chef',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_outlet.address'),
        ),
    ]
