# Generated by Django 4.1 on 2022-09-02 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
